---

ansible_user: "ec2-user"
ansible_ssh_private_key_file: "../../terraform/environments/staging/vm_key"
bastion_key:  "../../terraform/environments/staging/bastion_key"
ansible_ssh_common_args: "-o ProxyCommand='ssh -i {{ bastion_key }} -W %h:%p -q ec2-user@{{ hostvars[groups['grp_bastion_host'][0]].public_ip_address }}'"
dest_folder : /var/www/html
s3_address: "https://staging-images-acs730-shadowy-inspiration.s3.amazonaws.com/ShadowyInspiration.jpg"
