---

ansible_user : "ec2-user"
ansible_ssh_private_key_file: "../../terraform/environments/production/bastion_key"
ansible_ssh_common_args: "-o ProxyCommand='ssh -i {{ ansible_ssh_private_key_file }} -W %h:%p -q ec2-user@{{ ansible_host }}'"
webserver_private_key: "../../terraform/environments/production/vm_key"
webserver_key_destination: "/home/ec2-user/.ssh/vm_key"